services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@4321
      MYSQL_DATABASE: UserData
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@4321
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    

  backend:
    build:
      context: .                     # The directory where Dockerfile is located
    container_name: goApp_container
    restart: always
    ports:
      - "8080:8080"                  # Expose the app on port 8080
    environment:
      DB_HOST: mysql                 # MySQL service name (DNS resolution via Docker network)
      DB_PORT: 3306                  # MySQL port
      DB_USER: root                  # MySQL user
      DB_PASSWORD: admin@4321        # MySQL password
      DB_NAME: UserData              # MySQL database name
    depends_on:
      - mysql                        # Ensure the MySQL container starts first
