CREATE DATABASE IF NOT EXISTS UserData;

USE UserData;

CREATE TABLE time_log (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    IP_address VARCHAR(45) NOT NULL,
    Logged_Time DATETIME NOT NULL
);